/*
 * This source file was generated by the Gradle 'init' task
 */
package todocli;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        final Task_Impl ti = new Task_Impl();
        final UserInputs usrInp = new UserInputs(ti);


        usrInp.askUserAction();
 


   }
}
