/*
 * This source file was generated by the Gradle 'init' task
 */
package todocli;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        final UserInputs usrInp = new UserInputs();

        System.out.println("say hello for me");
        System.out.print(">>");

        usrInp.askUserAction();
    }
}
